---
title: "Small Lit Review"
output: pdf_document
---

A paper from [@frost_effects] studies the effects of being old ($65 \leq$) vs young ($18 -40$) and the effects of sex on single dose apixaban (20 mg). Estimated pharmacokinetic parameters show the elderly had higher CMAX, AUC, half life, and smaller apparent clearance than their younger counterparts.  Effects of sex were small, with males having lower Cmax, AUC, half life, and higher apparent clearance.  The authors conclude that the differences are not clinically meaningful and that dose adjustment is not needed.

From a 2019 review of apixaban:
* Cmax was similar in a study between young and old patients, however AUC was 32% higher in the elderly subjects.  Study showed a relationship between apixaban clearance and creatinine clearance, suggesting that renal funtion may have contributed to the differences in exposure between groups (i.e. Perhaps kidney function degraded in older subjects).

* Study shoes Cmax and AUC are higher in females as compared to males.  $AUC = D/Cl$ so perhaps sex appears in clearance only?  Especially considering there appear to be no differences in tmax (or atleast, we have not detected differences).

* Subjects with body weight less than 50 kg had 27%/20% higher Cmax/AUC compared with reference group.  Those with body weight larger than 120 kg had 31%/23% lower Cmax and AUC as compared with reference group

---
references:
- id: frost_effects
  title: Effects of age and sex n the single dose pharmacokinetics and pharmacodynamics of apixaban
  author:
  - family: Frost
    given: Charles
  container-title: Clinical Pharmacokinetics
  volume: 11
  URL: 'http://dx.doi.org/10.1038/nmat3283'
  DOI: 10.1038/nmat3283
  issue: 4
  publisher: Clinical Pharmacokinetics
  issued:
    year: 2015
---

